apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nodejs-ex
    name: nodejs-ex
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nodejs-ex
    name: nodejs-ex
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: nodejs-ex:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/sclorg/nodejs-ex.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:latest
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: dCniWkkVe54qrcI208uw
      type: GitHub
    - generic:
        secret: oFbyN9isuFqNxOQ4s4iq
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nodejs-ex
    name: nodejs-ex
  spec:
    replicas: 5
    selector:
      app: nodejs-ex
      deploymentconfig: nodejs-ex
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: nodejs-ex
          deploymentconfig: nodejs-ex
      spec:
        containers:
        - image: nodejs-ex:latest
          name: nodejs-ex
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - nodejs-ex
        from:
          kind: ImageStreamTag
          name: nodejs-ex:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nodejs-ex
    name: nodejs-ex
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: nodejs-ex
      deploymentconfig: nodejs-ex
  status:
    loadBalancer: {}
kind: List
metadata: {}
